import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        content: {
          DEFAULT: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          placeholder: "var(--text-placeholder)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          light: "var(--primary-light)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar-background)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
        // Button theme colors
        "btn-primary": "var(--btn-primary)",
        "btn-primary-hover-bg": "var(--btn-primary-hover-bg)",
        "btn-primary-active-bg": "var(--btn-primary-active-bg)",
        "btn-success": "var(--btn-success)",
        "btn-success-hover-bg": "var(--btn-success-hover-bg)",
        "btn-success-active-bg": "var(--btn-success-active-bg)",
        "btn-error": "var(--btn-error)",
        "btn-error-hover-bg": "var(--btn-error-hover-bg)",
        "btn-error-active-bg": "var(--btn-error-active-bg)",
        "btn-highlight": {
          DEFAULT: "var(--btn-highlight)",
          text: "var(--btn-highlight-text)",
        },
        "btn-highlight-hover-bg": "var(--btn-highlight-hover-bg)",
        "btn-highlight-active-bg": "var(--btn-highlight-active-bg)",
        "btn-muted-hover-bg": "var(--btn-muted-hover-bg)",
        "btn-muted-active-bg": "var(--btn-muted-active-bg)",
        "btn-dark-hover-bg": "var(--btn-dark-hover-bg)",
        "btn-dark-active-bg": "var(--btn-dark-active-bg)",
        // Interactive surfaces
        "surface-hover": "var(--surface-hover)",
        "surface-active": "var(--surface-active)",
        // Banner colors
        "banner-info": "var(--banner-info-bg)",
        "banner-success": "var(--banner-success-bg)",
        "banner-warning": "var(--banner-warning-bg)",
        "banner-error": "var(--banner-error-bg)",
        "banner-text": "var(--banner-text)",
        "banner-info-icon": "var(--banner-info-icon)",
        "banner-success-icon": "var(--banner-success-icon)",
        "banner-warning-icon": "var(--banner-warning-icon)",
        "banner-error-icon": "var(--banner-error-icon)",
        "banner-info-link": "var(--banner-info-link)",
        "banner-success-link": "var(--banner-success-link)",
        "banner-warning-link": "var(--banner-warning-link)",
        "banner-error-link": "var(--banner-error-link)",
        // Chip colors
        "chip-bg": "var(--chip-bg)",
        "chip-border": "var(--chip-border)",
        "chip-text": "var(--chip-text)",
        "chip-hover-bg": "var(--chip-hover-bg)",
        "chip-hover-border": "var(--chip-hover-border)",
        "chip-active-bg": "var(--chip-active-bg)",
        "chip-active-border": "var(--chip-active-border)",
        "chip-pressed-bg": "var(--chip-pressed-bg)",
        "chip-filled-bg": "var(--chip-filled-bg)",
        "chip-filled-text": "var(--chip-filled-text)",
        "chip-filled-hover-bg": "var(--chip-filled-hover-bg)",
        "chip-filled-pressed-bg": "var(--chip-filled-pressed-bg)",
        "chip-filled-active-bg": "var(--chip-filled-active-bg)",
        // Radio colors
        "radio-border": "var(--radio-border)",
        "radio-hover": "var(--radio-hover)",
        "radio-checked": "var(--radio-checked)",
        "radio-checker": "var(--radio-checker)",
        // Checkbox colors
        "checkbox-border": "var(--checkbox-border)",
        "checkbox-hover": "var(--checkbox-hover)",
        "checkbox-checked": "var(--checkbox-checked)",
        "checkbox-icon": "var(--checkbox-icon)",
        // Toggle colors
        "toggle-unchecked": "var(--toggle-unchecked)",
        "toggle-checked": "var(--toggle-checked)",
        "toggle-checker": "var(--toggle-checker)",
        // Badge colors
        "badge-default": "var(--badge-default)",
        "badge-default-border": "var(--badge-default-border)",
        "badge-default-text": "var(--badge-default-text)",
        "badge-primary": "var(--badge-primary)",
        "badge-primary-text": "var(--badge-primary-text)",
        "badge-success": "var(--badge-success)",
        "badge-success-text": "var(--badge-success-text)",
        "badge-error": "var(--badge-error)",
        "badge-error-text": "var(--badge-error-text)",
        "badge-highlight": "var(--badge-highlight)",
        "badge-highlight-text": "var(--badge-highlight-text)",
        "badge-dark": "var(--badge-dark)",
        "badge-dark-text": "var(--badge-dark-text)",
        "badge-primary-light-bg": "var(--badge-primary-light-bg)",
        "badge-primary-light-text": "var(--badge-primary-light-text)",
        "badge-success-light-bg": "var(--badge-success-light-bg)",
        "badge-success-light-text": "var(--badge-success-light-text)",
        "badge-error-light-bg": "var(--badge-error-light-bg)",
        "badge-error-light-text": "var(--badge-error-light-text)",
        "badge-highlight-light-bg": "var(--badge-highlight-light-bg)",
        "badge-highlight-light-text": "var(--badge-highlight-light-text)",
        "badge-dark-light-bg": "var(--badge-dark-light-bg)",
        "badge-dark-light-text": "var(--badge-dark-light-text)",
        "badge-muted": "var(--badge-muted)",
        "badge-muted-text": "var(--badge-muted-text)",
        "badge-muted-light-bg": "var(--badge-muted-light-bg)",
        "badge-muted-light-text": "var(--badge-muted-light-text)",
        // Card colors
        "design-card": "var(--design-card)",
        "design-card-border": "var(--design-card-border)",
        "design-card-primary-bg": "var(--design-card-primary-bg)",
        "design-card-highlight-bg": "var(--design-card-highlight-bg)",
        // Divider colors
        "divider": "var(--divider)",
        "spacing-bg": "var(--spacing-bg)",
        // Navigation colors
        "nav-none": {
          DEFAULT: "var(--nav-none)",
          title: "var(--nav-none-title)",
        },
        "nav-primary": {
          DEFAULT: "var(--nav-primary)",
          title: "var(--nav-primary-title)",
        },
        "nav-dark": {
          DEFAULT: "var(--nav-dark)",
          title: "var(--nav-dark-title)",
        },
        "nav-transparent-title": "var(--nav-transparent-title)",
        // InputBar colors
        "inputbar": "var(--inputbar-bg)",
        "inputbar-text": "var(--inputbar-text)",
        "inputbar-placeholder": "var(--inputbar-placeholder)",
        "inputbar-icon": "var(--inputbar-icon)",
        "inputbar-cursor": "var(--inputbar-cursor)",
        // Input colors
        "input-bg": "var(--input-bg)",
        "input-value": "var(--input-value)",
        "input-title": "var(--input-title)",
        "input-placeholder": "var(--input-placeholder)",
        "input-icon": "var(--input-icon)",
        "input-cursor": "var(--input-cursor)",
        "input-border-color": "var(--input-border-color)",
        "input-focus": "var(--input-focus)",
        // Cell colors
        "cell-hover": "var(--cell-hover)",
        "cell-active": "var(--cell-active)",
        // Rating colors
        "rating-star": "var(--rating-star)",
        "rating-empty": "var(--rating-empty)",
        "rating-text": "var(--rating-text)",
        "tooltip-bg": "var(--tooltip-bg)",
        "tooltip-text": "var(--tooltip-text)",
        "highlight-tint": "var(--highlight-tint)",
        // Button extended
        "btn-muted": "var(--btn-muted)",
        "btn-dark": "var(--btn-dark)",
        // PromoBanner
        "promo-bg": "var(--promo-bg)",
        "promo-text": "var(--promo-text)",
        "promo-action": "var(--promo-action)",
        "promo-overlay": "var(--promo-overlay)",
        // Color scales
        "primary-default": "var(--primary-default)",
        "primary-dark": "var(--primary-dark)",
        "primary-extra-dark": "var(--primary-extra-dark)",
        "primary-medium": "var(--primary-medium)",
        "success-default": "var(--success-default)",
        "success-dark": "var(--success-dark)",
        "success-extra-dark": "var(--success-extra-dark)",
        "success-medium": "var(--success-medium)",
        "success-light": "var(--success-light)",
        "success-extra-light": "var(--success-extra-light)",
        "highlight-default": "var(--highlight-default)",
        "highlight-dark": "var(--highlight-dark)",
        "highlight-extra-dark": "var(--highlight-extra-dark)",
        "highlight-medium": "var(--highlight-medium)",
        "highlight-light": "var(--highlight-light)",
        "highlight-extra-light": "var(--highlight-extra-light)",
        "error-default": "var(--error-default)",
        "error-dark": "var(--error-dark)",
        "error-extra-dark": "var(--error-extra-dark)",
        "error-medium": "var(--error-medium)",
        "error-extra-light": "var(--error-extra-light)",
        "greyscale-1": "var(--greyscale-1)",
        "greyscale-2": "var(--greyscale-2)",
        "greyscale-3": "var(--greyscale-3)",
        "greyscale-4": "var(--greyscale-4)",
        "greyscale-5": "var(--greyscale-5)",
        "greyscale-6": "var(--greyscale-6)",
        "bloom-muted": "var(--text-subtle)",
        "bloom-dark": "var(--text-strong)",
        // Documentation colors
        docs: {
          bg: "var(--docs-bg)",
          foreground: "var(--docs-foreground)",
          heading: "var(--docs-heading)",
          muted: "var(--docs-muted)",
          border: "var(--docs-border)",
          code: "var(--docs-code)",
          "code-text": "var(--docs-code-text)",
          "preview-header": "var(--docs-preview-header)",
        },
      },
      opacity: {
        "48": "0.48",
      },
      boxShadow: {
        "card-lifted": "0px 4px 12px rgba(21, 25, 26, 0.12)",
        "card-elevated": "0px 4px 16px rgba(21, 25, 26, 0.24)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;